//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Climbox.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int Id { get; set; }
        public string DireccionGym { get; set; }
        public string TelefonoGym { get; set; }
        public string NombreGym { get; set; }
    }
}
